### ISSUE TITLE
User not removed from the location user list until manual refresh

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#23]
As location admin, if I remove a user from the list of users authorized for the given location, the user still appears in the list of authorized users for the location. A refresh removes the user from the page too

User is present
![screen shot 2014-07-08 at 19 58 24](https://cloud.githubusercontent.com/assets/7584397/3514147/8a62dab4-06c9-11e4-9ecb-24fff5ba2dea.png)

Removing the user...
![screen shot 2014-07-08 at 19 58 34](https://cloud.githubusercontent.com/assets/7584397/3514150/92b3fd10-06c9-11e4-9201-ce466a8b73fd.png)

User is still in the list
![screen shot 2014-07-08 at 19 58 40](https://cloud.githubusercontent.com/assets/7584397/3514155/9b27b3f6-06c9-11e4-8404-ba4af5d41c7f.png)

A refresh, and the user disappears from the list
![screen shot 2014-07-08 at 19 59 36](https://cloud.githubusercontent.com/assets/7584397/3514166/ac68ed2e-06c9-11e4-8601-e9b02c9cb0e9.png)

**Comment by GDeviceLab** [comment]
It works on Admins colums, but not on Users column

**Comment by revevol-italy** [comment]
Fixed
