### ISSUE TITLE
Send an email to location admins where a new user ask to access to their location

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#32]
Having more than one location admin needs to be considered

**Comment by GDeviceLab** [comment]
Email body should be improved. 

Actual text is:
- - -
Dear location Admin,
the user alfredomorresi@google.com asks to apply to Revevol.

Please, access to Device Lab Management application.
- - -

Desired text should be
- - -
Dear location Admin,
the user %user_name% \<%user_email%\> from %StartupName% asks to apply to Revevol.

Please, access to Device Lab Management application here %link_to_users_page_for_given_location% to approve or reject the user.
- - -

So a location admin can have a comprensive overview of the new request and with only a click can access to the app and authorise the new user.

**Comment by revevol-italy** [comment]
Fixed

**Comment by GDeviceLab** [comment]
Mail sent to location admin has a simple https://rev-cal.appspot.com/ as link.

Wondering if it's possible to link directly the page where the location admin can accept/reject the user, instead of the general devicelab page (%link_to_users_page_for_given_location%)
