### ISSUE TITLE
User name should be mandatory when registering

### ISSUE THREAD

**Issue by avermeulen** [GDeviceLab/DeviceLab#34]
Be sure that a new user that register need to add their user details as in Name and Surname. 
We had a scenario where a user registered without supplying any details it just display "undefined undefined" in that case

**Comment by GDeviceLab** [comment]
Email body should be improved. 

Actual text is:
- - -
Dear location Admin,
the user alfredomorresi@google.com asks to apply to Revevol.

Please, access to Device Lab Management application.
- - -

Desired text should be
- - -
Dear location Admin,
the user %user_name% \<%user_email%\> from %StartupName% asks to apply to Revevol.

Please, access to Device Lab Management application here %link_to_users_page_for_given_location% to approve or reject the user.
- - -

So a location admin can have a comprensive overview of the new request and with only a click can access to the app and authorise the new user.
