### ISSUE TITLE
The "Available Devices" window too small and confused

### ISSUE THREAD

**Issue by Pikatan** [GDeviceLab/DeviceLab#45]
The window displaying the available devices is way too small. When the number grows to 20-30 devices, it will be very hard to browse through them.

![available devices](https://cloud.githubusercontent.com/assets/9053211/4545215/2611425a-4e39-11e4-9b75-66fed688fd85.PNG)

**Comment by GDeviceLab** [comment]
> In addition, a left arrow should be present on the first day and a right arrow on the last day of the days panel

Cannot see the arrows.

In addition, a very small arrow has been added on top of month name to compress the month view. It's hard to click in the desktop app and pretty much impossible in the touch-friendly version of the app. To compress the month view, clicking on the month name should be enough.

**Comment by GDeviceLab** [comment]
There is no clue that you can click on the month name to compress the month panel.

"Previous week" and "Next week" labels are wrong. Clicking on them they don't jump to next or previous week, but to next or previous 5 days. Please change the title accordingly and also consider what the labels should show when the app is displayed in a touch interface

**Comment by revevol-italy** [comment]
Fixed

**Comment by GDeviceLab** [comment]
The month panel doesn't work on Firefox. Not tested on other browser apart Chrome.

In touch interface mode, "next" and "prev" browsing buttons disappeared
