### ISSUE TITLE
Reporting for global project usage required

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#47]
Global admin should have access to the following new reports

- Global usage for locations, in terms of devices, time etc
- Tested Android app / website / other purposes for locations (see #49 for more detail)

In addition to the criteria expressed on #46 , also the selection of locations (one, more, all) should be present. All/none button to select all locations is a must ;)

**Comment by GDeviceLab** [comment]
The "tested purposes" report has some information missed
![screen shot 2015-01-09 at 15 54 14](https://cloud.githubusercontent.com/assets/7584397/5681317/dc417004-9817-11e4-8638-43c22fe58ffd.png)
What's the column header? I suppose "number of booking for the given purposes".

Is it possible to use the same metrics used in the "Global usage for locations" report, so number of hours and reservation number?

**Comment by GDeviceLab** [comment]
As said, please use same metrics and layout of other reports, like "Global usage for locations".

Using the long header "Global usage for locations" and just concatenating strings isn't the best solution, user point of view.

**Comment by revevol-italy** [comment]
fixed
