### ISSUE TITLE
Need to track the android apps / website used while testing

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#49]
One data that should be tracked by DeviceLab is the android apps or websites that startups tested using provided devices.

One way to achieve this is to add a new "purpose" field to the booking page and asking what will be tested. In case of an android app, it's package name, in case of a website, it's site public address.

In order to check the input of the field, an option can show if the booking is for testing a mobile app / or a website / or other. Then the purpose field can show a tooltip like "Enter your app id" or "Enter the website address" or "Enter the purpose" respectively.

In order to facilitate this data entry (that may be very boring), a new booking should have that fields pre-populated with the value used in the past booking by the same person and the purpose field should show, if required, a list of all the values used in the past bookings.

**Comment by GDeviceLab** [comment]
There is no visual feedback of the fact that fields are mandatory or values are empty, but required, when the user try to save the booking. Similar for device(s) field.

The "Your saved purposes" section is not working, it mixed the value of name fields for mobile and web purposes. 

Change "Purpose" field label with "You want to test..."

**Comment by revevol-italy** [comment]
1) Added Visual Feedback for mandatory Purpose fields
2) Changed "Purpose" Label

We have not met error in the Purpose widget:
- When a new reservation is created, the last saved Purpose is configured
- Using the Select Widget is possibile to change with another saved Purpose
- Creating a new Purpose save it into the list of Purpose and it is immediately ready for the next Reservation
- The Values of the name are correctly shown in the dropdown , in the input widget and they are correctly saved  into the Datastore.

Please could you give more detail about the issue?

Thanks

**Comment by GDeviceLab** [comment]
Try that:

- Create a new reservation
- Specify mobile app
- Specify it.rainbowbreeze.testapp as package name
- Save

- Create a new reservation
- Open the "Save purposes" combobox: "Mobile App - it.rainbowbreeze.it" is shown 
- Change to Website
- Open the "Save purposes" combobox: "Website - it.rainbowbreeze.it" is shown  <- Wrong
- Don't select any "Save purposes", simply close the combobox
- Specify it.rainbowbreeze.testapp as package name
- Save

and so on...

In addition, if create a new reservation, change package name (let's say it.rainbowbreeze.testapp2) and save, the next reservation hasn't anymore the saved purpose "Mobile app - it.rainbowbreeze.testapp" but only the new purpose "Mobile app - it.rainbowbreeze.testapp2"

Also the -New purpose- item in the combobox is misleading, because by default the empty item of the combobox is shown.

**Comment by revevol-italy** [comment]
Fixed

**Comment by GDeviceLab** [comment]
Please verify this feature. it still doesn't work

**Comment by GDeviceLab** [comment]
Still some small bug:

Steps to riproduce
* Create a reservation with a website (or mobile) purpose
* Edit the reservation
* Select "Other" as purpose -> name field is cleared
Save

Instead, if I create a new reservation and select Other as purpose, leaving the name field blank and saving, an error appears saying that I need to fill the name purpose.

What's the expected behaviour for "Other purpose"? Blank name or filled name? I would prefer filled name but no memories in the saved purposes combo.

In addition, in reports, these white purposes create different entries instead of a unique voice with aggregate data
![screen shot 2015-01-23 at 16 43 40](https://cloud.githubusercontent.com/assets/7584397/5877396/9fce430a-a31f-11e4-97c7-e8b280f8068a.png)

**Comment by revevol-italy** [comment]
We have fixed the bug in the edit mode of the Reservation, so:
- For new and edit Reservations it controls always the name value
- For "Other" purpose is always need a not empty name as the others types
- Report review now shoudn't present empty name (according with the fix resolved).
