### ISSUE TITLE
Footer should be customized location-based

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#51]
Every location should have a customized footer image that can be customized, so we can add different partner / logos for every location. Is nothing is present, the default footer is taken in account (it can be defined by a global admin).

This parameter can be set in a new section, available to global admin and location admin.

**Comment by GDeviceLab** [comment]
When I upload a picture, no process or visual feedback is shown.

There is no info on the right size of the picture to upload.

Where there is a Chrome logo when no picture has been uploaded?

Even if I upload a big picture, a very small thumbnail of it is shown
![screen shot 2015-01-07 at 19 01 35](https://cloud.githubusercontent.com/assets/7584397/5650542/9fabdb08-969f-11e4-9ef2-425a28aa4857.png)

**Comment by GDeviceLab** [comment]
3) I've made a mistake. 

My original question would have been "Why there is a Chrome logo when no picture has been uploaded?". Maybe it's Chome itself or a placeholder image used in the code.

**Comment by revevol-italy** [comment]
Correct, it's a placeholder method that injects the image when nothing is already uploaded.

Should we change it with a Classic "Google" name logo?

**Comment by GDeviceLab** [comment]
For sure we need to define a standard image for all the location when a customised one is not specified.

Please leave the standard image and, once we have the final logo, we'll use it.
