### ISSUE TITLE
Menu names should match with section names

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#52]
If I click on left-menu "Users", a page with "Location - XXXX" title is shown. Same for "Devices" menu, with the title of the page set to "Asset".

Menu names and pages name should match

**Comment by revevol-italy** [comment]
Users List View is shown and managed inside the Location Edit Page. So currently we have two cases for accessing to the same view: 1. clicking on the Users button 2. clicking on the Locations button and after to the specific Location Name.

The title of the page respects perfectly the 2nd case.

Following some fixing proposal:
a) make dynamic name of the title (even if make no-sense a "Users" title having its bottom page that contains also location controls, maybe we could change Title Name and remove location control at the same time)
b) move the Users Control in another menu section
c) remove the users menu button and let the local Admin to access to the location list managed by him (verify if it already works in this way)

**Comment by GDeviceLab** [comment]
I'm not following...

What about changing:
* "Users" button text in "Manage location"
* "Asset - " title to "Devices - " in the "Devices" page
* "News - " title to "Add news - " in the "Add News" page

and, but it's less important
* "Stats - " title to "My Stats - " in the "My statistics" page

In that way, all the buttons refer to a matching section title, and vice versa

**Comment by GDeviceLab** [comment]
News menu open a page with title "Add News" - please change it to "News"
