### ISSUE TITLE
Calendar has only 8-18 time. Cannot book outside this time

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#54]
Is impossible to book a device outside this timespan, even in the book detail page the time are fixed from 7.30 to 18.30

**Comment by revevol-italy** [comment]
Fixed

**Comment by GDeviceLab** [comment]
Booking near 24 doesn't work.

Steps:
* Calendar window, drag mouse from 23:00 to 24:00 and release the mouse
* Reservation window is opened
* in From field, 23h30 is displayed

To field is empty, it should be pre-populated with the right time

**Comment by GDeviceLab** [comment]
In addition, new interface has hours that are in the middle of lines, so it's not easy to understand what time a particular timeslot refers to
![screen shot 2015-01-20 at 18 40 53](https://cloud.githubusercontent.com/assets/7584397/5822415/2f80e7f8-a0d4-11e4-99cc-eb3a33db4c44.png)
 
Google Calendar uses a different UI, where is clear the link between slots and hours
![screen shot 2015-01-20 at 18 41 47](https://cloud.githubusercontent.com/assets/7584397/5822424/4a5a1e78-a0d4-11e4-9d2c-657f2170a6d4.png)
