### ISSUE TITLE
[Code] Adding timezone property to a location

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#62]
Every location should have also a timezone property.

There are two places where it should be possibile to edit this info:

1) When creating a new location
![screen shot 2015-01-26 at 15 53 54](https://cloud.githubusercontent.com/assets/7584397/5901593/f4fb88aa-a573-11e4-9098-e57a502a7fdb.png)

2) When editing an existing location
![screen shot 2015-01-26 at 15 54 09](https://cloud.githubusercontent.com/assets/7584397/5901612/183d9f88-a574-11e4-93e9-464c4773bbc3.png)

Please use a combobox with all the possible locations to input the value

**Comment by GDeviceLab** [comment]
How do I save the timezone for an already-existing location? The save button seems unavailable for location admin, as per screenshot below:
![screen shot 2015-02-13 at 19 16 50](https://cloud.githubusercontent.com/assets/7584397/6192700/fc0ae9c0-b3b4-11e4-84c7-ccc8df72d857.png)

**Comment by revevol-italy** [comment]
We've not met the same issue: Please could you find to clean the browser cache?
(Below this is our result)
![screen shot 2015-02-17 at 18 05 14](https://cloud.githubusercontent.com/assets/4662465/6233017/502d14ce-b6d0-11e4-85fc-2c7bcef0c7d1.png)
