### ISSUE TITLE
After the deploy of the new version of the app (3), past reservations are no more visible

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#65]
It seems that only reservations created with the new app version are visible, but not past ones.

For example, First Round Capital made some reservations the first 5 days of January, as for report, but nothing is shown on its calendar.

**Comment by revevol-italy** [comment]
After deploying the new release committed, the ADMIN has to launch the Servlet  "/AlignmentServlet" using this link: https://devicelab-app.appspot.com/AlignmentServlet
If the response is a positive message, the reservations are now correctly updated and now they shoud be visible in the calendar
