### ISSUE TITLE
Logo of the starred location is in the left menu, not the current one

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#69]
Only the logo of the starred location is shown in the left menu, despite the location the user currently selected.

This is not an issue if a user has just one location, but it is when the user has more than one location to select
![screenshot from 2015-02-04 16 55 10](https://cloud.githubusercontent.com/assets/7584397/6043851/8f526bd6-ac8f-11e4-8e6e-007b17f728b6.png)

**Comment by revevol-italy** [comment]
After a refresh of the browser, the user now remains in the same location.
Example: If a user has a favourite B location and he's in A location, after refreshing the page now he remains in the A location
