### ISSUE TITLE
[UI] [Mobile] There is no clue that left side of calendar can be used to scroll down the whole view

### ISSUE THREAD

**Issue by GDeviceLab** [GDeviceLab/DeviceLab#76]
![screenshot_2015-02-10-17-32-00](https://cloud.githubusercontent.com/assets/7584397/6194163/ce7aebce-b3c1-11e4-9ec5-eb72271309d0.png)

In the calendar page, there is no clue that, to scroll down, the left part of the screen have to be used, the one with the hours.
I tried different times, but I always end up creating a new reservation.

**Comment by etaheri** [comment]
This has been fixed by changing the size of the calendar.
